name: Run Tailscale
description: Runs Tailscale
branding:
  icon: activity
  color: blue
inputs:
  version:
    description: 'Tailscale version (defaults to latest)'
    required: true
    default: 1.30.0 # renovate
  accept-routes:
    description: 'Accept subnet routes that other nodes advertise'
    required: false
    default: 'true'
  authkey:
    description: 'Tailscale auth key'
    required: true
  hostname:
    description: 'Provide a hostname to use for the device'
    required: false
  shields-up:
    description: 'Block incoming connections from other devices on your Tailscale network'
    required: false
    default: 'true'
  args:
    description: 'Optional additional arguments to ''tailscale up'''
    required: false

runs:
  using: composite
  steps:

    - shell: bash
      env:
        VERSION: ${{ inputs.version }}
        ACCEPT_ROUTES: ${{ inputs.accept-routes == 'true' }}
        AUTHKEY: ${{ inputs.authkey }}
        HOSTNAME: ${{ inputs.hostname }}
        SHIELDS_UP: ${{ inputs.shields-up == 'true' }}
        ADDITIONAL_ARGS: ${{ inputs.args }}
        OWNER: ${{ github.event.repository.owner.login }}
        REPO_NAME: ${{ github.event.repository.name }}
        RUN_ID: ${{ github.run_id }}
      run: |
        minor=$(echo "$VERSION" | awk -F '.' {'print $2'})
        if [ $((minor % 2)) -eq 0 ]; then
          url="https://pkgs.tailscale.com/stable/tailscale_${VERSION}_amd64.tgz"
        else
          url="https://pkgs.tailscale.com/unstable/tailscale_${VERSION}_amd64.tgz"
        fi
        wget -q "$url" -O /tmp/tailscale.tgz
        mkdir /tmp/tailscale
        tar -C /tmp/tailscale --strip-components 1 -xzf /tmp/tailscale.tgz

        sudo /tmp/tailscale/tailscaled 2>~/tailscaled.log &
        if [ -z "${HOSTNAME}" ]; then
          HOSTNAME="gh-actions-$OWNER_NAME-$REPO-$(sum=$(echo -n "$RUN_ID" | sha256sum) && echo ${sum::4})"
        fi
        sudo /tmp/tailscale/tailscale up \
          --accept-routes=$ACCEPT_ROUTES \
          --authkey="$AUTHKEY" \
          --hostname="$HOSTNAME" \
          --shields-up=$SHIELDS_UP \
          ${ADDITIONAL_ARGS}
