name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    if: startsWith( github.event.head_commit.message, 'Update dependency tailscale/tailscale to' )
    runs-on: ubuntu-latest
    steps:

      - name: Determine Release Version
        id: release-version
        env:
          REPO: ${{ github.repository }}
        run: |
          previous=$(
            version=$(
              curl \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$REPO/releases/latest" | \
              jq -r '.name'
            ) && \
            echo ${version#v}
          )
          previous_segments=(${previous//./ })
          previous_major=${previous_segments[0]}
          previous_minor=${previous_segments[1]}
          previous_patch=${previous_segments[2]}
          patch=$(($previous_patch + 1)) 
          version="$previous_major.$previous_minor.$patch"
          echo "::set-output name=version::$version"
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with: 
          name: v${{ steps.release-version.outputs.version }}
          tag_name: v${{ steps.release-version.outputs.version }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
