name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
